### ISSUE TITLE
Tiffs can't be drag/dropped into Project Tree (MacOS)

### ISSUE THREAD

**Issue by inhalt120g** [VilleKrumlinde/zgameeditor#16]
After drag/dropping a tiff image into Project Tree, nothing happens.

jpg, bmp and png  files work normally (select a file in Finder, drag into Project Tree, release lmb…  creates a new Bitmap  / BitmapFromFile component Project Tree entry).

**Comment by VilleKrumlinde** [comment]
Hi, tiff is not a supported format. Ideally it would show an error when trying to read it (maybe it does this on Windows version).
