### ISSUE TITLE
Unexpected Tab behavior in Expression editor (MacOS)

### ISSUE THREAD

**Issue by inhalt120g** [VilleKrumlinde/zgameeditor#25]
Pressing Tab in the ZExpression adds unequal amount of space. Sometimes it's just two spaces, other times the cursor jumps over 8 places. I can't figure out what does it depend upon (I see that it's context sensitive and trying to match the indentation of other text but very often it's not clear where will the cursor jump).

In these examples I press Tab equal amount of times in both lines but the results are completely different:
![zge 画面収録 008 tab variation](https://user-images.githubusercontent.com/106015575/172689088-b3398c83-989d-4baa-a2d5-458632a2f048.gif)
![zge 画面収録 007 tab variation](https://user-images.githubusercontent.com/106015575/172689090-4988478f-8bdb-48c3-9d58-1112a2cf4b75.gif)

**Comment by inhalt120g** [comment]
When a portion of the code is selected, pressing Tab adds indentation. But here, it just deletes the text (swaps the text with one tab to be precise).

**Comment by Blue-EyesWhiteDragon** [comment]
Apple Silicon or Intel?
