### ISSUE TITLE
Files not filtered in file requester (MacOS)

### ISSUE THREAD

**Issue by inhalt120g** [VilleKrumlinde/zgameeditor#30]
When opening files (File / Open): the file requester has a filter (under "Options") that is meant to hide all non-zgeproj files. When activated, non-zgeproj files can still be seen.

**Comment by VilleKrumlinde** [comment]
I think this is how File dialogs on Mac OS works? If I compare with other applications it behaves the same. Other files are visible but grayed out so they are not selectable.

**Comment by inhalt120g** [comment]
Sorry I was imprecise and didn't describe it properly at all (the files can be seen but can't be selected). Let me retry that!

You are right, that's how the file requester works. In ZGE it works like that too, for example if in the same folder there are a bmp, png and zgeproj files… the bitmaps will not be selectable. 

But if in the same folder there are some builds too, they can be easily selected and ZGE will try to open them, but then abort with an error report. For example here I can freely select the build files despite the filter being set to ZGE files only:
![スクリーンショット 2022-10-01 1 31 50](https://user-images.githubusercontent.com/106015575/193369415-46ad8790-72fe-4f59-8883-4487db75bd6a.png)

So it's really easy to attempt to open a build by mistake (for some reason I automatically click on builds instead of the ZGE files when I open a file requester).
