### ISSUE TITLE
Keyboard shortcuts change depending on the cursor position (MacOS)

### ISSUE THREAD

**Issue by inhalt120g** [VilleKrumlinde/zgameeditor#35]
Some parts of ZGE use Windows keyboard shortcuts, other parts use local OS keyboard shortcuts.

In ZExpression, copy / paste keyboard shortcuts are mapped to Control+V (using Windows convention).
But IDE property fields (for example in RenderTransform.Comment field) use "standard" keyboard shortcuts (Command+V).

The XML Editor is using the Windows convention… but then Expression evaluator (the input field below trace console) is using MacOS convention.

In ZExpression, standard keyboard cursor controls for jumping to the beginning / end of the line don't work (I assume Command + left/right would work but that's a system shortcut for switching desktops) but the same commands for jumping to the next word or start/end of the line work in other parts of the IDE (both Alt + cursor keys and Control + cursor keys).

**Comment by VilleKrumlinde** [comment]
Copy/paste shortcuts will use Mac convention in next build.
