### ISSUE TITLE
Icons rendered as black shapes (MacOS)

### ISSUE THREAD

**Issue by inhalt120g** [VilleKrumlinde/zgameeditor#36]
Almost all the icons are rendered as black shapes. For example, in toolbar:
![image](https://user-images.githubusercontent.com/106015575/195880486-1fb52747-5594-4953-ac89-365c135ae623.png)

The only two icons that are rendered properly are the "colored grid" icon (used for SetColor component) and the "generic three dots" (used for BitmapBlur, Bitmap Cells… ImplicitCombine, ImplicitExpression…).

**Comment by VilleKrumlinde** [comment]
This is fixed now.
