### ISSUE TITLE
Assertion failure c:/ZGameEditor/tools/ZDesigner/frmEditor.pas line 2774

### ISSUE THREAD

**Issue by Txori** [VilleKrumlinde/zgameeditor#7]
I compiled new ZGE source code using Delphi to obtain ZDesigner.exe and player.bin, both 64 bits.
But when I run the project in ZGE, I get that error message:

Assertion failure c:/ZGameEditor/tools/ZDesigner/frmEditor.pas line 2774

Which correspond to 
Assert(R<>nil);
in procedure TEditorForm.ReplaceResource(const ExeFile,OutFile,DataFile : string; UseCodeRemoval : boolean);

**Comment by VilleKrumlinde** [comment]
It seems to work here. I use "makeplayer.bat" in ZGE folder to build x64 player.bin using Freepascal.
